Diana
VanyaRPP/task-monitoring-app pull request #104
Opened 2022-07-27 14:07 UTC by GorDi004

2022-07-27 16:18 UTC, Iangyl requested changes

2022-07-27 16:18 UTC, Iangyl commented on common/components/ApplyAuctionForm/index.tsx
> +          { required: true, message: 'Будь ласка, введіть суму грошей!' },
Введіть ціну послуги

2022-07-27 16:18 UTC, Iangyl commented on common/components/CompetitionWorkerCard/index.tsx
> +        <p>Ім`я: {user?.name || user?.email}</p>
apostrophe

2022-07-27 16:18 UTC, Iangyl commented on common/components/UI/Steps/index.tsx
> +  return <div> </div>
What is it?

2022-07-29 09:30 UTC, GorDi004 commented on common/components/UI/Steps/index.tsx
> +  return <div> </div>
It is future element for Steps.

2022-07-29 09:30 UTC, GorDi004 commented on common/components/ApplyAuctionForm/index.tsx
> +          { required: true, message: 'Будь ласка, введіть суму грошей!' },
Ok

2022-07-31 21:59 UTC, merged