Fix bug with themes switcher for mobile version
VanyaRPP/task-monitoring-app pull request #131
Opened 2022-08-09 10:04 UTC by GorDi004

2022-08-09 19:26 UTC, VanyaRPP commented on common/components/CardOneTask/index.tsx
> +  // ]
Separete component

2022-08-11 14:57 UTC, GorDi004 commented on common/components/CardOneTask/index.tsx
> +  // ]
Ok

2022-08-11 17:10 UTC, Iangyl requested changes

2022-08-11 17:10 UTC, Iangyl commented on common/assets/features/validators.ts
> +    message: "Назва обов'язкова!",
Does it a universal method? We should be more concrete, for example: "Поле email обов'язкове!"

2022-08-11 17:10 UTC, Iangyl commented on common/components/CardOneTaskTable/index.tsx
> +  ]
eject to separate file, please

2022-08-11 17:10 UTC, Iangyl commented on common/components/ListOneTask/index.tsx
> +  // console.log(tasks)
remove log

2022-08-15 09:50 UTC, merged