Price list
VanyaRPP/task-monitoring-app pull request #586
Opened 2024-07-12 13:21 UTC by SerhiiDenysiuk23

2024-07-12 16:11 UTC, VanyaRPP approved these changes

2024-07-17 17:59 UTC, vakot commented
@SerhiiDenysiuk23 Join your changes from https://app.asana.com/0/1202389032764573/1207815014175852 here and we will merge them together

2024-07-22 07:57 UTC, vakot requested changes

2024-07-22 07:57 UTC, vakot commented on common/api/paymentApi/payment.api.types.ts
Remove changes not associated to this pull request

2024-07-22 07:57 UTC, vakot commented on common/components/DashboardPage/blocks/paymentComponents/PaymentSummary.tsx
Remove changes not associated to this pull request

2024-07-22 07:57 UTC, vakot commented on common/components/DashboardPage/blocks/paymentComponents/PaymentTableContent.tsx
Remove changes not associated to this pull request

2024-07-22 07:57 UTC, vakot commented on common/components/DashboardPage/blocks/payments.tsx
Remove changes not associated to this pull request

2024-07-22 07:57 UTC, vakot commented on common/components/Forms/AddPaymentForm/PriceList/numberToWords.ts
Move this logic to utils/helpers.ts. Also add some JSDoc to functions to easily understand their purposes

2024-07-22 07:57 UTC, vakot commented on common/components/UI/PaymentCardHeader/index.tsx
Remove changes not associated to this pull request

2024-07-22 07:57 UTC, vakot commented on common/components/Forms/AddPaymentForm/PriceList/data.ts
> +// ];
Remove unused comments

2024-07-22 07:57 UTC, vakot commented on common/components/Forms/AddPaymentForm/PriceList/data.ts
> +export const data = [{
This is test data, right? So rename it to something more self explainable. Or, if it`s unused - remove it

2024-07-22 07:57 UTC, vakot commented on common/components/Forms/AddPaymentForm/PriceList/index.tsx
> +  console.log(payment)
Remove unexpected `console.log()`

2024-07-22 07:58 UTC, vakot commented
Also check your autoformatter settings to match our project settings in `.prettierrc.json`, please

2024-07-29 08:57 UTC, vakot approved these changes

2024-08-07 14:12 UTC, merged