company filter changes for role admin
VanyaRPP/task-monitoring-app pull request #587
Opened 2024-07-12 17:46 UTC by TAMOTO24

2024-07-15 11:22 UTC, VanyaRPP approved these changes

2024-07-16 16:32 UTC, vakot requested changes

2024-07-16 16:32 UTC, vakot commented on common/components/DashboardPage/blocks/payments.tsx
> +  });
Need some condition to NOT render as link on http://localhost:3000. Render as link only on http://localhost:3000/payment

2024-07-16 16:32 UTC, vakot commented on common/components/DashboardPage/blocks/payments.tsx
> +              console.log("awdawd", i)
Get rid of `console.log()` please

2024-07-16 17:59 UTC, vakot approved these changes

2024-07-16 18:12 UTC, merged