fixed all filters
VanyaRPP/task-monitoring-app pull request #644
Opened 2024-08-15 21:24 UTC by SerhiiDenysiuk23

2024-08-15 21:26 UTC, VanyaRPP approved these changes

2024-08-16 08:53 UTC, vakot requested changes

2024-08-16 08:53 UTC, vakot commented on pages/api/service/index.ts
> +          ])
Your `Promise.all` has 2 promises inside it, but your response array expects 3. Move rest of your requests inside this `Promise.all` to increase performace.

```
const [relatedDomains, relatedStreets, distinctYears, distinctMonths] =
  await Promise.all([
    Domain.find({ _id: { $in: distinctDomains } }).select(['name', '_id']),

    Street.find({ _id: { $in: distinctStreets } }).select(['address', 'city', '_id']),

    Service.distinct('date', options).then((dates) => [
      ...new Set(dates.map((date) => new Date(date).getFullYear())),
    ]),

    Service.aggregate([
      { $match: options },
      { $group: { _id: { month: { $month: '$date' } } } },
      { $sort: { '_id.month': 1 } },
    ]).then((results) => [
      ...new Set(results.map((result) => result._id.month)),
    ]),
  ])
```

2024-08-16 08:53 UTC, vakot commented on pages/api/service/index.ts
> +        ])
Move this requests inside `Promise.all` to increase performace

2024-08-19 09:43 UTC, merged